### ISSUE TITLE
Execute custom workflows and custom commands on selected instances

### ISSUE THREAD

**Issue by loicalbertin** [ystia/yorc#107]
As: An app manager
I want to: execute a workflow or a custom command on a specific instance or set of instances, while currently it is executed on all instances
So that: I can have a better control on runtime operations

AC1: works for both workflows and custom commands

**Comment by adidanes** [comment]
### Executing custom commands on selected instances 
Currently Alien4Cloud operation execution model only allows to select one target instance, not one or more instances. 
Till now, the yorc-a4c-plugin plugin didn't used this possibility, the operation are executed on all the instances. We can use it now and thus allow to select an instance, but it will not be possible to select several instaces (see https://github.com/alien4cloud/alien4cloud/blob/develop/alien4cloud-core/src/main/java/alien4cloud/paas/model/NodeOperationExecRequest.java)
