### ISSUE TITLE
Support provisioning through an ssh "bastion"

### ISSUE THREAD

**Issue by loicalbertin** [ystia/yorc#128]
As: an operator
I want: be able to provision nodes even if they are not accessible directly through ssh
So that: I can be able to deploy an application in an environment that do not support direct ssh access

AC1: Use ssh bastion for Ansible
AC2: Use this kind of bastion for terraform when checking if the node is available

**Comment by loicalbertin** [comment]
> Dear @loicalbertin ,
> 
Hi @trihoangvo 
Sorry for the delay.

> Q1: This feature request was created in Dec 2018. Do you have any milestones set for this important feature?
No this is not planed yet, the issue was created only to keep track on it

> Q2: Can users keep the bastion host (and shut it down) or destroy it after provisioning?
> 
Provisioning using a bastion has several implications, appart from the numbers of infrastructures we should implement it on, the main attention point IMHO is our implementation of monitoring policies. Indeed, Yorc has an optional monitoring mechanism that allows to check services liveness, this should also support bastion some way and would require the bastion host to be always up. Anyway having monitoring checks from outside a given location seems to be a bad idea.

So for a short answer I think the bastion will need to be up only during provisioning phases and monitoring should be handle carefully or not be used at all in this kind of setup.

Hope this helps
Loïc

> Best,
> Tri

**Comment by trihoangvo** [comment]
Dear @loicalbertin ,

yes, I agree with you. The bastion host should only up during provisioning phases. Have you thought about the update phase, which requires the bastion host as well (to have a complete picture)?

**Comment by loicalbertin** [comment]
On updates a bastion should be present.
We can think about two ways to define the bastion to use for provisioning:
It could be done by adding parameters to the infrastructures part of Yorc configuration which will work great for static bastions or we can model it in TOSCA which is more flexible.
With TOSCA modeling we can even think about a having a specific topology modifier in Alien4Cloud that will add the creation/configuration of the bastion host at the beginning of the process and deleting it when we are done (something like that as reusing bastions for several provisioning may be interesting).

**Comment by trihoangvo** [comment]
It's great to have your view on this.

Actually, we are thinking about to modify a topology with a "bastion" node type. However, a user may be surprised, why his topology has a new compute node. Furthermore, this is likely a solution only for a particular TOSCA orchestration engine (e.g., Cloudify does not have this issue).

Therefore, we think, may be it is better for Yorc to provision a bastion host for a private network (if a bastion node does not exist in the topology). And finally, Yorc brings it down after provisioning. As a result, users are not aware (and do not need to know) about such details.

I am still reading the codes... still do not know how to modify an existing workflow... If you can point me to the right direction, it would be great!
