### ISSUE TITLE
Documentation mistake for OS infrastructure

### ISSUE THREAD

**Issue by BertrandD** [ystia/yorc#136]
# Issue Type

* Documentation issue report

## Description

In the documentation for the OpenStack infrastructure (https://yorc.readthedocs.io/en/stable/configuration.html#openstack). For the parameter `default_security_groups` it says : ` It should be a comma-separated list of security group names` but in the given above this section, the parameter is an array of string. 

We should check if a comma-separated list of security group names is still working or not.

## Output of `yorc version`

```
Yorc Server v3.0.0
Revision: "862087810474d4281168e5f18c526e3a3bc062ac"
```
## Priority

High / Medium / Low

* Low = We will consider this on our next sprint planning.

**Comment by loicalbertin** [comment]
Ok from my remembering `default_security_groups` should be:
- a list of string when specified in a config file:
in YAML
```yaml
infrastructures: 
  openstack:
    default_security_groups: ["default", "openbar"]
```
or in JSON
```json
"infrastructures": {
  "openstack": {
     "default_security_groups": ["default", "openbar"]
   }
}
```
- a coma-separated list or multi-valuated flag when using it as the command line
```bash
yorc server --infrastructure_openstack_default_security_groups=some,different,sg --infrastructure_openstack_default_security_groups=some_others
```
- a coma-separated list when used as an env variable
```bash
INFRA_OPENSTACK_DEFAULT_SECURITY_GROUPS=some,different,sg  yorc server```

Does it clarify? Did you experienced an unexpected behavior with this?

**Comment by BertrandD** [comment]
Yes it clarify ! 
I didn't have any issue, I just found that the doc was unclear

**Comment by loicalbertin** [comment]
Could you suggest an improvement based on above details?

**Comment by loicalbertin** [comment]
Well, closing this :snowflake: frozen issue :snowflake:
