### ISSUE TITLE
If a requirement property is not defined, Yorc fails to resolve it

### ISSUE THREAD

**Issue by gavillom** [ystia/yorc#170]
# Issue Type

Put an X between the brackets of the corresponding issue type

* [x] Bug report
* [ ] Documentation issue report
* [ ] Improvement request

## Description
I tried to deploy an Elasticsearch - Logstash topology. I don't need any proxy to connect both together so I didn't set the new relationship property proxy.
When I do that, the deployment fails with the following error : 

[2018-10-02T09:28:49.610201927Z][DEBUG][logstash-elsatic-Environment][install][8fe84459-6dfe-49b7-8f52-24bcb2c93d3b][Logstash][0][configure][pre_configure_source][]operation failed
[2018-10-02T09:28:49.658070011Z][INFO][logstash-elsatic-Environment][install][8fe84459-6dfe-49b7-8f52-24bcb2c93d3b][Logstash][0][][][]Status for node "Logstash", instance "0" changed to "error"
[2018-10-02T09:28:49.6771158Z][DEBUG][logstash-elsatic-Environment][install][8fe84459-6dfe-49b7-8f52-24bcb2c93d3b][Logstash][][][][]Step "Logstash_logstashToElasticsearchElasticsearchSearch_resource_pre_configure_source": error details: Can't resolve expression "get_property: [SELF, proxy]"
github.com/ystia/yorc/deployments.(*functionResolver).resolveGetPropertyOrAttribute
        /home/a454241/go/src/github.com/ystia/yorc/deployments/resolver.go:308
github.com/ystia/yorc/deployments.(*functionResolver).resolveFunction
        /home/a454241/go/src/github.com/ystia/yorc/deployments/resolver.go:132
github.com/ystia/yorc/deployments.GetOperationInput
        /home/a454241/go/src/github.com/ystia/yorc/deployments/operations.go:586
github.com/ystia/yorc/prov/operations.ResolveInputsWithInstances
        /home/a454241/go/src/github.com/ystia/yorc/prov/operations/inputs.go:117
github.com/ystia/yorc/prov/ansible.(*executionCommon).resolveInputs
        /home/a454241/go/src/github.com/ystia/yorc/prov/ansible/execution.go:663
github.com/ystia/yorc/prov/ansible.(*executionCommon).resolveExecution
        /home/a454241/go/src/github.com/ystia/yorc/prov/ansible/execution.go:675
github.com/ystia/yorc/prov/ansible.newExecution
        /home/a454241/go/src/github.com/ystia/yorc/prov/ansible/execution.go:225
github.com/ystia/yorc/prov/ansible.(*defaultExecutor).ExecOperation
        /home/a454241/go/src/github.com/ystia/yorc/prov/ansible/executor.go:66
github.com/ystia/yorc/tasks/workflow.(*step).runActivity.func2
        /home/a454241/go/src/github.com/ystia/yorc/tasks/workflow/workflow.go:368
github.com/ystia/yorc/tasks/workflow.(*step).runActivity
        /home/a454241/go/src/github.com/ystia/yorc/tasks/workflow/workflow.go:369
github.com/ystia/yorc/tasks/workflow.(*step).run.func2
        /home/a454241/go/src/github.com/ystia/yorc/tasks/workflow/workflow.go:267
github.com/ystia/yorc/tasks/workflow.(*step).run
        /home/a454241/go/src/github.com/ystia/yorc/tasks/workflow/workflow.go:280
github.com/ystia/yorc/tasks/workflow.worker.processWorkflow.func1.1
        /home/a454241/go/src/github.com/ystia/yorc/tasks/workflow/worker.go:88
github.com/ystia/yorc/vendor/golang.org/x/sync/errgroup.(*Group).Go.func1
        /home/a454241/go/src/github.com/ystia/yorc/vendor/golang.org/x/sync/errgroup/errgroup.go:58
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1333
[2018-10-02T09:28:49.831013011Z][ERROR][logstash-elsatic-Environment][install][8fe84459-6dfe-49b7-8f52-24bcb2c93d3b][][][][][]Error 'Can't resolve expression "get_property: [SELF, proxy]"' happened in workflow "install".
[2018-10-02T09:28:49.921345202Z][INFO][logstash-elsatic-Environment][install][8fe84459-6dfe-49b7-8f52-24bcb2c93d3b][][][][][]Status for deployment "logstash-elsatic-Environment" changed to "deployment_failed"

## Expected behavior
The deployment doesn't fail. Proxy resolution value should be empty.
## Actual behavior
The deployment fails with above error
## Steps to reproduce the issue

1. Create an application based on the following topology.[LogstashElsatic_0.1.0-SNAPSHOT.zip](https://github.com/ystia/yorc/files/2437324/LogstashElsatic_0.1.0-SNAPSHOT.zip)
2. Try to deploy it : this should fails on Logstash.pre_configure_source operation

## Additional environment details (infrastructure implied: AWS, OpenStack, etc.)
Tested on Openstack

## Output of `yorc version`
Yorc Server v3.1.0-M3
Revision: "e284e247de79f39504522fcb33955a99351ea1de"

A4C version 2.0.0
## Yorc configuration file
consul: {address: '127.0.0.1:8500'}
http_port: '8800'
ansible:
  use_openssh: true
infrastructures:
  openstack:
    auth_url: http://10.197.135.201:5000/v2.0
    default_security_groups: [default]
    password: Star16.gs
    private_network_name: private-test
    tenant_name: starlings
    user_name: starlings
resources_prefix: demo-
server_id: yorc-a4c-yorc-0.novalocal
terraform: {plugins_dir: /var/terraform/plugins}

## Priority

High

* High = We should stop anything we are doing and do this. If you're writing this calmly, you should probably choose another option. If it's really that urgent, please make sure we read this.
* Medium = It's important that we do this within a few days.
* Low = We will consider this on our next sprint planning.

(Please be aware that your priority may not match ours, we'll use this as guidance only).

**Comment by gavillom** [comment]
Same issue trying to initialize the property into Alien4Cloud with an empty value (A4C doesn't propose to save the topology either).

**Comment by stebenoist** [comment]
It seems Alien4Cloud doesn't support empty strings "" for default values. Yorc does -)

**Comment by stebenoist** [comment]
An issue and a PR have been created about this issue.
https://github.com/alien4cloud/alien4cloud/issues/169
https://github.com/alien4cloud/alien4cloud/pull/170

**Comment by stebenoist** [comment]
Merged in A4C
