### ISSUE TITLE
Should generate unique names for Compute Instances created on demand on Google Cloud 

### ISSUE THREAD

**Issue by laurentganne** [ystia/yorc#177]
# Issue Type

* [X] Bug report
* [ ] Documentation issue report
* [ ] Improvement request

## Description

When you create a topoloy in Alien4Cloud, adding a tosca.nodes.Compute element, its default name will be: `Compute`
When this topology is deployed on google, a compute instance `prefix-compute-0` is created.

Then when you attempt to deploy another toplogy built the same way, with a `tosca.nodes.Compute` element keeping the default name `Compute`,
the deployment will fail with this error :

```
Error: Error applying plan:

1 error(s) occurred:

* google_compute_instance.prefix-compute-0: 1 error(s) occurred:

* google_compute_instance.prefix-compute-0: Error creating instance: googleapi: Error 409: The resource 'projects/myproject/zones/europe-west1-b/instances/prefix-compute-0' already exists, alreadyExists

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.



[2018-10-17T08:44:57.670030349Z][INFO][essai2-Environment][install][62a978f8-078c-46fc-adca-fa2c61d23da8][Compute][0][][][]Status for node "Compute", instance "0" changed to "error"
[2018-10-17T08:44:57.678756785Z][DEBUG][essai2-Environment][install][62a978f8-078c-46fc-adca-fa2c61d23da8][Compute][][][][]TaskStep "Compute_install": error details: exit status 1
Failed to apply the infrastructure changes via terraform
github.com/ystia/yorc/prov/terraform.(*defaultExecutor).applyInfrastructure
	/home/travis/gopath/src/github.com/ystia/yorc/prov/terraform/executor.go:225
github.com/ystia/yorc/prov/terraform.(*defaultExecutor).installNode
	/home/travis/gopath/src/github.com/ystia/yorc/prov/terraform/executor.go:93
github.com/ystia/yorc/prov/terraform.(*defaultExecutor).ExecDelegate
	/home/travis/gopath/src/github.com/ystia/yorc/prov/terraform/executor.go:72
```

## Expected behavior

To have a consistent behaviour in User experience on other infrastructures like OpenStack, where the user doesn't have to care about the unicity of the Compute node name in his topology template,
Yorc should generate a unique name for the compute instances it generates on demand, for example by adding the deployment name in the compute instance name.

## Output of `yorc version`

Happens since 3.0.0

## Priority

Low

Needed in release 3.1

**Comment by loicalbertin** [comment]
As we should take care of not having too long names for computes as it used as hostname and an unix hostname can't exceed 63 characters, I propose to hash the deployment id using the sha1 algorithm and use only the 5 or so first chars.

This way we will have:
- the same prefix for all resources within a deployment
- if some resources were not properly deleted on previous deployments an error will occur that should be taken into account 
- 7 to 5 supplementary chars sounds reasonable (should avoid most of potential collisions but stay around 10% of the max length)
