### ISSUE TITLE
Upgrade Ansible to version 2.7

### ISSUE THREAD

**Issue by adidanes** [ystia/yorc#194]
**As:** Yorc team
**I want to:** upgrade to 2.7 anible version
**So that:** I can benefit from updates in the crypto modules

**AC1:** Be able to generate certificates using an own CA

**Comment by loicalbertin** [comment]
We should check for deprecations

**Comment by adidanes** [comment]
When testing deployment of Consul with Yorc, I identified 2 warning types:

1. Using tests as filters is deprecated. Instead of using `result|changed` use `result is changed`. Remove in **2.9**
2. Invoking "yum" or "apt" (or ...) only once while using a loop via squash_actions is deprecated. Instead of using a loop to supply multiple items and specifying `name: {{item}}`, please use `name: [u'zip', u'unzip']` and remove the loop. Remove in **2.11**
