### ISSUE TITLE
No output properties for services on GKE

### ISSUE THREAD

**Issue by Loic-R** [ystia/yorc#214]
# Issue Type

Put an X between the brackets of the corresponding issue type

* [X] Bug report
* [ ] Documentation issue report
* [ ] Improvement request

## Expected behavior
See ip and node port of the service in alien output properties

## Actual behavior
Output properties diplays : "N/A"

## Steps to reproduce the issue

1. Configure a yorc/alien with a kubernetes infrastructure
2. Deploy any kubernetes topology that have an associated service

## Additional information you deem important (e.g. issue happens only occasionally)
It seems that it comes from this line : https://github.com/ystia/yorc/blob/develop/prov/kubernetes/execution.go#L362

## Additional environment details (infrastructure implied: AWS, OpenStack, etc.)
Infra : Kubernetes on google cloud engine

**Comment by loicalbertin** [comment]
Resolved per #223
