### ISSUE TITLE
IP missing for k8s_service_url in runtime view - GKE

### ISSUE THREAD

**Issue by Loic-R** [ystia/yorc#215]
# Issue Type

Put an X between the brackets of the corresponding issue type

* [X] Bug report
* [ ] Documentation issue report
* [ ] Improvement request

## Description
When deploying an app with alien, on GKE infra ; in runtime view, IP is missing for "k8s_service_url" attribute. 

## Expected behavior
k8s_service_url should display "http://IP:PORT"

## Actual behavior
Actually when apps are deployed it displays "http://:PORT"

## Steps to reproduce the issue

1. Have a correctly configured yorc and alien with kubernetes on GKE location
2. Deploy any app associated with a service (simple appache for example)

## Additional information you deem important (e.g. issue happens only occasionally)
Seems coming from : https://github.com/ystia/yorc/blob/develop/prov/kubernetes/execution.go#L362 

## Additional environment details (infrastructure implied: AWS, OpenStack, etc.)
Infra : Kubernetes on GKE

**Comment by loicalbertin** [comment]
Closed per #219
