### ISSUE TITLE
Add to Yorc documentation info about providing ssh credentials to connect to target infrastructures

### ISSUE THREAD

**Issue by adidanes** [ystia/yorc#221]
# Issue Type

Put an X between the brackets of the corresponding issue type

* [ ] Bug report
* [x] Documentation issue report
* [ ] Improvement request

## Description

- Document general issue about connecting in ssh to hosts, VMs, etc, where Yorc deploys applications.
- Instruct the user (the Yorc administrator) that ssh keys must be generated with "DER"/"Distinguished Encoding Rules" 
- Its probably necessary to also update the Alien Yorc plugin documentation 

## Priority

Low

* High = We should stop anything we are doing and do this. If you're writing this calmly, you should probably choose another option. If it's really that urgent, please make sure we read this.
* Medium = It's important that we do this within a few days.
* Low = We will consider this on our next sprint planning.

(Please be aware that your priority may not match ours, we'll use this as guidance only).

**Comment by stebenoist** [comment]
Everything is already well-described for each location with specific information about credentials.
Just added a known issue about BER private key format.
