### ISSUE TITLE
K8S jobs namespace should not be removed if its provided

### ISSUE THREAD

**Issue by adidanes** [ystia/yorc#245]
# Issue Type

Put an X between the brackets of the corresponding issue type

* [x] Bug report
* [ ] Documentation issue report
* [ ] Improvement request

## Description
User can provide a namespace name for the application to be deployed. When the application contains K8S Jobs, the Jobs should run in the context of the provided namespace, and when the job ends, the namespace still remains.

## Expected behavior
When the job ennds, the namespace should remain.

## Actual behavior
The namespace is deleted when the job ends.

## Steps to reproduce the issue

1. Step1
2. Step2 ...

## Output of `yorc version`
V3.1.0-RC2

## Priority

Low

* High = We should stop anything we are doing and do this. If you're writing this calmly, you should probably choose another option. If it's really that urgent, please make sure we read this.
* Medium = It's important that we do this within a few days.
* Low = We will consider this on our next sprint planning.

(Please be aware that your priority may not match ours, we'll use this as guidance only).

**Comment by loicalbertin** [comment]
Should be backported to 3.1.1 release.
