### ISSUE TITLE
Slurm Accounting

### ISSUE THREAD

**Issue by loicalbertin** [ystia/yorc#280]
**As:** a admin
**I want to:** follow accounting for Slurm Jobs/Computes
**So that:** I can go ahead with the billing

**AC1:** Allow to customize billing account in TOSCA
**AC2:** No account by default
**AC3:** Should provide a config option that enforces accounting (disabled by default).
**AC4:** Doc update

**Comment by stebenoist** [comment]
Missing accounting for Slurm compute
