### ISSUE TITLE
Migrate to alien4cloud-yorc-provider

### ISSUE THREAD

**Issue by loicalbertin** [ystia/yorc#428]
**As:** Yorc dev team
**I want to:** migrate to https://github.com/alien4cloud/alien4cloud-yorc-provider
**So that:** We can contribute to the official Alien4Cloud plugin for Yorc

**AC1:** Check that https://github.com/alien4cloud/alien4cloud-yorc-provider contains all needed features
**AC2:** Implement missing features (SSL connexion, Slurm Accounting & reservation, K8S persistent volume claim, anti-affinity placement policy for Openstack, monitoring services liveness)
**AC3:** prepare a plan to migrate existing setups from one plugin to another

**Comment by adidanes** [comment]
This issue contains the following tasks :
- Add features that exist in Ystia's yorc plugin (alien4cloud-yorc-plugin) to Alien4Cloud's new yorc plugin (alien4cloud-yorc-provider). This task corresponds to the Alien4Cloud PR https://github.com/alien4cloud/alien4cloud-yorc-provider/pull/3
- Add a new Tosca component definition for the Alien4Cloud's new yorc plugin. This task correspons to the Ystia Forge PR https://github.com/ystia/forge/pull/102
- Use the new Tosca component in the Yorc's bootstrap. This task corresponds to the Ystia Yorc PR https://github.com/ystia/yorc/pull/496/. 

The validation of the third task allows to validate the first two ones also.

**Comment by adidanes** [comment]
This issue implies that we need to migrate documentation from the Ystia's yorc plugin to the Alien's documentation (http://alien4cloud.github.io/#/documentation/2.1.0/orchestrators/yorc/index.html)

**Comment by adidanes** [comment]
Other task: migrate tosca-samples from yorc-a4c-plugin to Forge (or elsewhere ?). Maybe some samples could be used in a user's guide, or tutorial...

**Comment by trihoangvo** [comment]
Dear @adidanes I would love to ask you one question if possible. I see the implementation between `yorc-a4c-plugin` and `alien4cloud-yorc-provider` looks different. Is it going to be a pure migration or there are something new in `alien4cloud-yorc-provider`?, any compability issues?

**Comment by loicalbertin** [comment]
Hi @trihoangvo,

We will release in next few days both Alien4Cloud 2.2.0-SM9 and Yorc 4.0.0-M4.
With those releases `alien4cloud-yorc-provider` will be iso-functional with `yorc-a4c-plugin`.
Even better you could expect `alien4cloud-yorc-provider` to be more reliable and scalable.
