### ISSUE TITLE
Refactor logs to allow to config new implementations

### ISSUE THREAD

**Issue by loicalbertin** [ystia/yorc#552]
**As:** An operator
**I want to:** allow to plug another backend for Yorc deployments logs
**So that:** I can adapt to my setup

**AC1:** Refactor to make it less dependent to the consul backend implementation
**AC2:** Consul backend should remain the default
**AC3:** Should be able to use Yorc plugins for backend implementations
**AC4:** Study if we can easily demonstrate an other backend implementation (ElasticSearch/Logstash seems to be a good candidate)

**Comment by stebenoist** [comment]
What if default implementation is file and we cipher the logs ?
