### ISSUE TITLE
Tosca public_ip_address attribute is wrongly set with private address for hosts pool computes

### ISSUE THREAD

**Issue by stebenoist** [ystia/yorc#593]
# Bug Report

## Description

Tosca public_ip_address attribute is wrongly set with private address for hosts pool computes

**Comment by loicalbertin** [comment]
Are you sure?
Have you properly setup [implicit labels](https://yorc.readthedocs.io/en/latest/infrastructures.html#implicit-filters-labels)?

**Comment by stebenoist** [comment]
Yep. See my incoming PR
