### ISSUE TITLE
Use of winrm instead of ssh to check a Windows compute instance connection

### ISSUE THREAD

**Issue by laurentganne** [ystia/yorc#704]
After Yorc has created an compute instance, it attempts to check its connection using ssh.
It could be interesting to be able to use winrm instead of ssh on Windows compute instances

**Comment by loicalbertin** [comment]
Yes but how will we distinguish linux vs windows instances.
Should we have a `WindowsCompute` TOSCA type?

**Comment by laurentganne** [comment]
Expecting it to be defined in the on demand compute instance resource where you spcify the image name, and other parameters like the  Provisinoning admin capability endpoint protocol and credentials.
The endpoint protocl could be ssh or winrm. Here in this code, I read the endpoint protocol and consider everything but winrm is ssh (as sometimes we place tcp here):
https://github.com/ystia/yorc/blob/feature/GH-704-winrm-connection/prov/terraform/commons/resources.go#L204

**Comment by loicalbertin** [comment]
Ok looks good!

**Comment by laurentganne** [comment]
Closing this issue for now, as Windows 10 and Windows Server 2019 can now have openssh easily configured: see https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse 
And in an heterogeneous infrastructure with linux and windows host, using ssh connections with private/pblic keys for all makes it simpler.
