### ISSUE TITLE
Initiate a Blog for Ystia opensource project with the GCP demo

### ISSUE THREAD

**Issue by loicalbertin** [ystia/yorc#73]
# Issue Type

Put an X between the brackets of the corresponding issue type

* [ ] Bug report
* [ ] Documentation issue report
* [X] Improvement request

## Description

Initiate a Blog for Ystia opensource project with the GCP demo

  * [X] create a site at https://ystia.github.io/
  * [X] create a blog at https://ystia.github.io/blog/
  * [X] Rework GCP sample to:
    *  [X] minimize prerequisites
     * [X] provide scripts automating the setup
  * [X] Add a blog entry describing how to use the sample

**Comment by laurentganne** [comment]
Blog post available at [Deploying an image detection application on Google Cloud](https://ystia.github.io/2018/08/14/gcp-sample-app.html)

**Comment by laurentganne** [comment]
Related issue on Yorc plugin where the application code and scripts are provided : https://github.com/ystia/yorc-a4c-plugin/issues/39
