### ISSUE TITLE
Manage applications secrets

### ISSUE THREAD

**Issue by loicalbertin** [ystia/yorc#90]
As: an app designer
I want to: handle secrets in a more secure way by not adding them into the topology
So that: I can prevent secrets stealing

AC1: consider the use of a new get_secret TOSCA operation to be defined

### Sub Tasks

- [x] Check that Alien and our plugin send the `get_secret` function correctly 
- [x] implement the `get_secret` function in the TOSCA functions resolver
- [x] Check if we can integrate with Ansible vault to prevent secrets from being wrote on the Orchestrator host in plain text 
- [x] refactor deployment package to expose if resolved tosca values are secret or not

**Comment by adidanes** [comment]
Branch feature/gh90 merged
