### ISSUE TITLE
Yorc is systematically no longer able to deploy after this kind of undeployment

### ISSUE THREAD

**Issue by loicalbertin** [ystia/yorc#95]
Reported by @billmetangmo on an pre-3.0 version.
To be checked if still relevant 

I have noticed that every time i undeploy an application that is waiting for slurm reservation resources ; as a consequence Janus is no longer able to deploy any app again

To reproduce the issue:

create a slurm partitions with 3 nodes
deploy an application with 2 nodes with ALien4Cloud
deploy the same application in another environment
undeploy it
try to deploy an app with 1 node

Regards

**Comment by stebenoist** [comment]
Not reproduced
